name: fitpulse_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # Custom libs.
  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  flutter_svg: ^2.2.3
  provider: ^6.1.5+1
  table_calendar: ^3.2.0
  flutter_colorpicker: ^1.1.0
  sqflite: ^2.4.2
  path: ^1.9.1

  # Firebase libs.
  # google_sign_in: ^7.2.0
  # firebase_auth: ^6.1.2
  # cloud_firestore: ^6.1.0
  # firebase_messaging: ^16.0.4
  # firebase_core: ^4.2.1
  # flutter_local_notifications: ^19.5.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Custom libs.
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  assets:
    - lib/assets/images/

  uses-material-design: true

flutter_launcher_icons:
  image_path: "lib/assets/images/favicon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/images/logo.png"
  android: true
  ios: true